"""LCFA public API."""

from .actions import RecommendationActionCompiler
from .engine import LCFA
from .operator_lib import ConstraintViolation, register_reasoning_operators
from .operators import register_core_operators
from .profile import Profile, ProfileError, load_profile
from .protocol import (
    ActionGraph,
    ActionNode,
    ActionResult,
    ActionRun,
    EntityRef,
    EvidenceRef,
    EvidenceValue,
    ExecutionContext,
    Finding,
    OperatorResult,
    PlanNode,
    ReasoningPlan,
    Recommendation,
    SolutionState,
)
from .registry import ActionRegistry, ActionSpec, OperatorRegistry, OperatorSpec
from .runtime import ActionExecutor, ActionPolicyError, PlanError, ReasoningExecutor
from .serde import (
    IR_FORMAT,
    SerializationError,
    dump_ir,
    dumps_ir,
    from_ir_dict,
    load_ir,
    loads_ir,
    to_ir_dict,
)
from .state import (
    MemoryStateStore,
    StateConflictError,
    StateIdentity,
    StateNotFoundError,
    StateSnapshot,
    StateStore,
    StateStoreError,
    canonical_bytes,
    content_hash,
)

__all__ = [
    "ActionExecutor",
    "ActionGraph",
    "ActionNode",
    "ActionPolicyError",
    "ActionRegistry",
    "ActionResult",
    "ActionRun",
    "ActionSpec",
    "ConstraintViolation",
    "EntityRef",
    "EvidenceRef",
    "EvidenceValue",
    "ExecutionContext",
    "Finding",
    "IR_FORMAT",
    "LCFA",
    "MemoryStateStore",
    "OperatorRegistry",
    "OperatorResult",
    "OperatorSpec",
    "PlanError",
    "PlanNode",
    "Profile",
    "ProfileError",
    "ReasoningExecutor",
    "ReasoningPlan",
    "Recommendation",
    "RecommendationActionCompiler",
    "SerializationError",
    "SolutionState",
    "StateConflictError",
    "StateIdentity",
    "StateNotFoundError",
    "StateSnapshot",
    "StateStore",
    "StateStoreError",
    "canonical_bytes",
    "content_hash",
    "dump_ir",
    "dumps_ir",
    "from_ir_dict",
    "load_ir",
    "load_profile",
    "loads_ir",
    "register_core_operators",
    "register_reasoning_operators",
    "to_ir_dict",
]
