"""LCFA public API."""

from .actions import RecommendationActionCompiler
from .bench import (
    BENCH_FORMAT,
    COMPARISON_FORMAT,
    REPORT_FORMAT,
    AssertionResult,
    BenchmarkCase,
    BenchmarkError,
    BenchmarkReport,
    BenchmarkRunner,
    BenchmarkSubject,
    BenchmarkSuite,
    BenchmarkSummary,
    CaseResult,
    ComparisonReport,
    ExpectedValue,
    ReasonerSubject,
    benchmark_report_from_dict,
    benchmark_report_to_dict,
    benchmark_suite_from_dict,
    benchmark_suite_to_dict,
    compare_reports,
    dump_benchmark_report,
    dump_benchmark_suite,
    dumps_benchmark_report,
    dumps_benchmark_suite,
    dumps_comparison,
    load_benchmark_report,
    load_benchmark_suite,
    loads_benchmark_report,
    loads_benchmark_suite,
)
from .engine import LCFA
from .operator_lib import ConstraintViolation, register_reasoning_operators
from .operators import register_core_operators
from .profile import Profile, ProfileError, load_profile
from .protocol import (
    ActionGraph,
    ActionNode,
    ActionResult,
    ActionRun,
    EntityRef,
    EvidenceRef,
    EvidenceValue,
    ExecutionContext,
    Finding,
    OperatorResult,
    PlanNode,
    ReasoningPlan,
    Recommendation,
    SolutionState,
)
from .registry import ActionRegistry, ActionSpec, OperatorRegistry, OperatorSpec
from .runtime import ActionExecutor, ActionPolicyError, PlanError, ReasoningExecutor
from .serde import (
    IR_FORMAT,
    SerializationError,
    dump_ir,
    dumps_ir,
    from_ir_dict,
    load_ir,
    loads_ir,
    to_ir_dict,
)
from .state import (
    MemoryStateStore,
    StateConflictError,
    StateIdentity,
    StateNotFoundError,
    StateSnapshot,
    StateStore,
    StateStoreError,
    canonical_bytes,
    content_hash,
)

__all__ = [
    "ActionExecutor",
    "ActionGraph",
    "ActionNode",
    "ActionPolicyError",
    "ActionRegistry",
    "ActionResult",
    "ActionRun",
    "ActionSpec",
    "AssertionResult",
    "BENCH_FORMAT",
    "BenchmarkCase",
    "BenchmarkError",
    "BenchmarkReport",
    "BenchmarkRunner",
    "BenchmarkSubject",
    "BenchmarkSuite",
    "BenchmarkSummary",
    "COMPARISON_FORMAT",
    "CaseResult",
    "ComparisonReport",
    "ConstraintViolation",
    "EntityRef",
    "EvidenceRef",
    "EvidenceValue",
    "ExecutionContext",
    "ExpectedValue",
    "Finding",
    "IR_FORMAT",
    "LCFA",
    "MemoryStateStore",
    "OperatorRegistry",
    "OperatorResult",
    "OperatorSpec",
    "PlanError",
    "PlanNode",
    "Profile",
    "ProfileError",
    "REPORT_FORMAT",
    "ReasonerSubject",
    "ReasoningExecutor",
    "ReasoningPlan",
    "Recommendation",
    "RecommendationActionCompiler",
    "SerializationError",
    "SolutionState",
    "StateConflictError",
    "StateIdentity",
    "StateNotFoundError",
    "StateSnapshot",
    "StateStore",
    "StateStoreError",
    "benchmark_report_from_dict",
    "benchmark_report_to_dict",
    "benchmark_suite_from_dict",
    "benchmark_suite_to_dict",
    "canonical_bytes",
    "compare_reports",
    "content_hash",
    "dump_benchmark_report",
    "dump_benchmark_suite",
    "dump_ir",
    "dumps_benchmark_report",
    "dumps_benchmark_suite",
    "dumps_comparison",
    "dumps_ir",
    "from_ir_dict",
    "load_benchmark_report",
    "load_benchmark_suite",
    "load_ir",
    "load_profile",
    "loads_benchmark_report",
    "loads_benchmark_suite",
    "loads_ir",
    "register_core_operators",
    "register_reasoning_operators",
    "to_ir_dict",
]
